[window]
decorations = "full"
opacity = 0.95
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 20

[window.padding]
x = 2
y = 2

[env]
TERM = "xterm-256color"

[shell]

[scrolling]
history = 100000

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14.0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = 36
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

