source ${HOME}/.zsh/antigen.zsh
if [ -e ${HOME}/.zshrc.local ] ; then
    source ${HOME}/.zshrc.local
fi

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load bundles from external repos
antigen bundles <<EOBUNDLES
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-completions
    git
    fzf
    Aloxaf/fzf-tab
    unixorn/fzf-zsh-plugin@main
EOBUNDLES

antigen theme fox

# Commit Antigen Configuration
antigen apply
